# Generated by Django 4.2.1 on 2024-04-14 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0002_auto_20201010_1633'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('F_Name', models.CharField(max_length=10)),
                ('M_Name', models.CharField(max_length=10)),
                ('L_Name', models.CharField(max_length=10)),
                ('Phone_No', models.CharField(max_length=14)),
                ('DOB', models.DateField(max_length=8)),
                ('Street', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Pincode', models.CharField(max_length=6)),
                ('is_patient', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_hospital', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('F_Name', 'M_Name', 'L_Name')},
            },
        ),
        migrations.CreateModel(
            name='Patient_Record',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=100, null=True)),
                ('P_Diagnostics', models.CharField(max_length=20)),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('Patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'unique_together': {('Patient', 'Doctor')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_Of_Appointment', models.DateField(max_length=8)),
                ('Medication', models.IntegerField()),
                ('Medicines', models.CharField(default=None, max_length=200, null=True)),
                ('Fee_Paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Ratings', models.IntegerField()),
                ('Patient_Record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient_record')),
            ],
        ),
    ]
